services:
  app:
    entrypoint:
    - sleep
    - infinity
    #image: archlinux:latest
    build:
      context: .
      target: development
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
