/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
/*
** QGL_WIN.C
**
** This file implements the operating system binding of GL to QGL function
** pointers.  When doing a port of Quake2 you must implement the following
** two functions:
**
** QGL_Init() - loads libraries, assigns function pointers, etc.
** QGL_Shutdown() - unloads libraries, NULLs function pointers
*/
#include <float.h>
#include "gl_local.h"

#include <GLFW/glfw3.h>

void(APIENTRY *qglAccum)(GLenum op, GLfloat value);
void(APIENTRY *qglAlphaFunc)(GLenum func, GLclampf ref);
GLboolean(APIENTRY *qglAreTexturesResident)(GLsizei n, const GLuint *textures, GLboolean *residences);
void(APIENTRY *qglArrayElement)(GLint i);
void(APIENTRY *qglBegin)(GLenum mode);
void(APIENTRY *qglBindTexture)(GLenum target, GLuint texture);
void(APIENTRY *qglBitmap)(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove,
                          const GLubyte *bitmap);
void(APIENTRY *qglBlendFunc)(GLenum sfactor, GLenum dfactor);
void(APIENTRY *qglCallList)(GLuint list);
void(APIENTRY *qglCallLists)(GLsizei n, GLenum type, const GLvoid *lists);
void(APIENTRY *qglClear)(GLbitfield mask);
void(APIENTRY *qglClearAccum)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void(APIENTRY *qglClearColor)(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
void(APIENTRY *qglClearDepth)(GLclampd depth);
void(APIENTRY *qglClearIndex)(GLfloat c);
void(APIENTRY *qglClearStencil)(GLint s);
void(APIENTRY *qglClipPlane)(GLenum plane, const GLdouble *equation);
void(APIENTRY *qglColor3b)(GLbyte red, GLbyte green, GLbyte blue);
void(APIENTRY *qglColor3bv)(const GLbyte *v);
void(APIENTRY *qglColor3d)(GLdouble red, GLdouble green, GLdouble blue);
void(APIENTRY *qglColor3dv)(const GLdouble *v);
void(APIENTRY *qglColor3f)(GLfloat red, GLfloat green, GLfloat blue);
void(APIENTRY *qglColor3fv)(const GLfloat *v);
void(APIENTRY *qglColor3i)(GLint red, GLint green, GLint blue);
void(APIENTRY *qglColor3iv)(const GLint *v);
void(APIENTRY *qglColor3s)(GLshort red, GLshort green, GLshort blue);
void(APIENTRY *qglColor3sv)(const GLshort *v);
void(APIENTRY *qglColor3ub)(GLubyte red, GLubyte green, GLubyte blue);
void(APIENTRY *qglColor3ubv)(const GLubyte *v);
void(APIENTRY *qglColor3ui)(GLuint red, GLuint green, GLuint blue);
void(APIENTRY *qglColor3uiv)(const GLuint *v);
void(APIENTRY *qglColor3us)(GLushort red, GLushort green, GLushort blue);
void(APIENTRY *qglColor3usv)(const GLushort *v);
void(APIENTRY *qglColor4b)(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
void(APIENTRY *qglColor4bv)(const GLbyte *v);
void(APIENTRY *qglColor4d)(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
void(APIENTRY *qglColor4dv)(const GLdouble *v);
void(APIENTRY *qglColor4f)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void(APIENTRY *qglColor4fv)(const GLfloat *v);
void(APIENTRY *qglColor4i)(GLint red, GLint green, GLint blue, GLint alpha);
void(APIENTRY *qglColor4iv)(const GLint *v);
void(APIENTRY *qglColor4s)(GLshort red, GLshort green, GLshort blue, GLshort alpha);
void(APIENTRY *qglColor4sv)(const GLshort *v);
void(APIENTRY *qglColor4ub)(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
void(APIENTRY *qglColor4ubv)(const GLubyte *v);
void(APIENTRY *qglColor4ui)(GLuint red, GLuint green, GLuint blue, GLuint alpha);
void(APIENTRY *qglColor4uiv)(const GLuint *v);
void(APIENTRY *qglColor4us)(GLushort red, GLushort green, GLushort blue, GLushort alpha);
void(APIENTRY *qglColor4usv)(const GLushort *v);
void(APIENTRY *qglColorMask)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void(APIENTRY *qglColorMaterial)(GLenum face, GLenum mode);
void(APIENTRY *qglColorPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void(APIENTRY *qglCopyPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
void(APIENTRY *qglCopyTexImage1D)(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width,
                                  GLint border);
void(APIENTRY *qglCopyTexImage2D)(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width,
                                  GLsizei height, GLint border);
void(APIENTRY *qglCopyTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
void(APIENTRY *qglCopyTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y,
                                     GLsizei width, GLsizei height);
void(APIENTRY *qglCullFace)(GLenum mode);
void(APIENTRY *qglDeleteLists)(GLuint list, GLsizei range);
void(APIENTRY *qglDeleteTextures)(GLsizei n, const GLuint *textures);
void(APIENTRY *qglDepthFunc)(GLenum func);
void(APIENTRY *qglDepthMask)(GLboolean flag);
void(APIENTRY *qglDepthRange)(GLclampd zNear, GLclampd zFar);
void(APIENTRY *qglDisable)(GLenum cap);
void(APIENTRY *qglDisableClientState)(GLenum array);
void(APIENTRY *qglDrawArrays)(GLenum mode, GLint first, GLsizei count);
void(APIENTRY *qglDrawBuffer)(GLenum mode);
void(APIENTRY *qglDrawElements)(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
void(APIENTRY *qglDrawPixels)(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
void(APIENTRY *qglEdgeFlag)(GLboolean flag);
void(APIENTRY *qglEdgeFlagPointer)(GLsizei stride, const GLvoid *pointer);
void(APIENTRY *qglEdgeFlagv)(const GLboolean *flag);
void(APIENTRY *qglEnable)(GLenum cap);
void(APIENTRY *qglEnableClientState)(GLenum array);
void(APIENTRY *qglEnd)(void);
void(APIENTRY *qglEndList)(void);
void(APIENTRY *qglEvalCoord1d)(GLdouble u);
void(APIENTRY *qglEvalCoord1dv)(const GLdouble *u);
void(APIENTRY *qglEvalCoord1f)(GLfloat u);
void(APIENTRY *qglEvalCoord1fv)(const GLfloat *u);
void(APIENTRY *qglEvalCoord2d)(GLdouble u, GLdouble v);
void(APIENTRY *qglEvalCoord2dv)(const GLdouble *u);
void(APIENTRY *qglEvalCoord2f)(GLfloat u, GLfloat v);
void(APIENTRY *qglEvalCoord2fv)(const GLfloat *u);
void(APIENTRY *qglEvalMesh1)(GLenum mode, GLint i1, GLint i2);
void(APIENTRY *qglEvalMesh2)(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
void(APIENTRY *qglEvalPoint1)(GLint i);
void(APIENTRY *qglEvalPoint2)(GLint i, GLint j);
void(APIENTRY *qglFeedbackBuffer)(GLsizei size, GLenum type, GLfloat *buffer);
void(APIENTRY *qglFinish)(void);
void(APIENTRY *qglFlush)(void);
void(APIENTRY *qglFogf)(GLenum pname, GLfloat param);
void(APIENTRY *qglFogfv)(GLenum pname, const GLfloat *params);
void(APIENTRY *qglFogi)(GLenum pname, GLint param);
void(APIENTRY *qglFogiv)(GLenum pname, const GLint *params);
void(APIENTRY *qglFrontFace)(GLenum mode);
void(APIENTRY *qglFrustum)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
GLuint(APIENTRY *qglGenLists)(GLsizei range);
void(APIENTRY *qglGenTextures)(GLsizei n, GLuint *textures);
void(APIENTRY *qglGetBooleanv)(GLenum pname, GLboolean *params);
void(APIENTRY *qglGetClipPlane)(GLenum plane, GLdouble *equation);
void(APIENTRY *qglGetDoublev)(GLenum pname, GLdouble *params);
GLenum(APIENTRY *qglGetError)(void);
void(APIENTRY *qglGetFloatv)(GLenum pname, GLfloat *params);
void(APIENTRY *qglGetIntegerv)(GLenum pname, GLint *params);
void(APIENTRY *qglGetLightfv)(GLenum light, GLenum pname, GLfloat *params);
void(APIENTRY *qglGetLightiv)(GLenum light, GLenum pname, GLint *params);
void(APIENTRY *qglGetMapdv)(GLenum target, GLenum query, GLdouble *v);
void(APIENTRY *qglGetMapfv)(GLenum target, GLenum query, GLfloat *v);
void(APIENTRY *qglGetMapiv)(GLenum target, GLenum query, GLint *v);
void(APIENTRY *qglGetMaterialfv)(GLenum face, GLenum pname, GLfloat *params);
void(APIENTRY *qglGetMaterialiv)(GLenum face, GLenum pname, GLint *params);
void(APIENTRY *qglGetPixelMapfv)(GLenum map, GLfloat *values);
void(APIENTRY *qglGetPixelMapuiv)(GLenum map, GLuint *values);
void(APIENTRY *qglGetPixelMapusv)(GLenum map, GLushort *values);
void(APIENTRY *qglGetPointerv)(GLenum pname, GLvoid **params);
void(APIENTRY *qglGetPolygonStipple)(GLubyte *mask);
const GLubyte *(APIENTRY *qglGetString)(GLenum name);
void(APIENTRY *qglGetTexEnvfv)(GLenum target, GLenum pname, GLfloat *params);
void(APIENTRY *qglGetTexEnviv)(GLenum target, GLenum pname, GLint *params);
void(APIENTRY *qglGetTexGendv)(GLenum coord, GLenum pname, GLdouble *params);
void(APIENTRY *qglGetTexGenfv)(GLenum coord, GLenum pname, GLfloat *params);
void(APIENTRY *qglGetTexGeniv)(GLenum coord, GLenum pname, GLint *params);
void(APIENTRY *qglGetTexImage)(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
void(APIENTRY *qglGetTexLevelParameterfv)(GLenum target, GLint level, GLenum pname, GLfloat *params);
void(APIENTRY *qglGetTexLevelParameteriv)(GLenum target, GLint level, GLenum pname, GLint *params);
void(APIENTRY *qglGetTexParameterfv)(GLenum target, GLenum pname, GLfloat *params);
void(APIENTRY *qglGetTexParameteriv)(GLenum target, GLenum pname, GLint *params);
void(APIENTRY *qglHint)(GLenum target, GLenum mode);
void(APIENTRY *qglIndexMask)(GLuint mask);
void(APIENTRY *qglIndexPointer)(GLenum type, GLsizei stride, const GLvoid *pointer);
void(APIENTRY *qglIndexd)(GLdouble c);
void(APIENTRY *qglIndexdv)(const GLdouble *c);
void(APIENTRY *qglIndexf)(GLfloat c);
void(APIENTRY *qglIndexfv)(const GLfloat *c);
void(APIENTRY *qglIndexi)(GLint c);
void(APIENTRY *qglIndexiv)(const GLint *c);
void(APIENTRY *qglIndexs)(GLshort c);
void(APIENTRY *qglIndexsv)(const GLshort *c);
void(APIENTRY *qglIndexub)(GLubyte c);
void(APIENTRY *qglIndexubv)(const GLubyte *c);
void(APIENTRY *qglInitNames)(void);
void(APIENTRY *qglInterleavedArrays)(GLenum format, GLsizei stride, const GLvoid *pointer);
GLboolean(APIENTRY *qglIsEnabled)(GLenum cap);
GLboolean(APIENTRY *qglIsList)(GLuint list);
GLboolean(APIENTRY *qglIsTexture)(GLuint texture);
void(APIENTRY *qglLightModelf)(GLenum pname, GLfloat param);
void(APIENTRY *qglLightModelfv)(GLenum pname, const GLfloat *params);
void(APIENTRY *qglLightModeli)(GLenum pname, GLint param);
void(APIENTRY *qglLightModeliv)(GLenum pname, const GLint *params);
void(APIENTRY *qglLightf)(GLenum light, GLenum pname, GLfloat param);
void(APIENTRY *qglLightfv)(GLenum light, GLenum pname, const GLfloat *params);
void(APIENTRY *qglLighti)(GLenum light, GLenum pname, GLint param);
void(APIENTRY *qglLightiv)(GLenum light, GLenum pname, const GLint *params);
void(APIENTRY *qglLineStipple)(GLint factor, GLushort pattern);
void(APIENTRY *qglLineWidth)(GLfloat width);
void(APIENTRY *qglListBase)(GLuint base);
void(APIENTRY *qglLoadIdentity)(void);
void(APIENTRY *qglLoadMatrixd)(const GLdouble *m);
void(APIENTRY *qglLoadMatrixf)(const GLfloat *m);
void(APIENTRY *qglLoadName)(GLuint name);
void(APIENTRY *qglLogicOp)(GLenum opcode);
void(APIENTRY *qglMap1d)(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
void(APIENTRY *qglMap1f)(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
void(APIENTRY *qglMap2d)(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2,
                         GLint vstride, GLint vorder, const GLdouble *points);
void(APIENTRY *qglMap2f)(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2,
                         GLint vstride, GLint vorder, const GLfloat *points);
void(APIENTRY *qglMapGrid1d)(GLint un, GLdouble u1, GLdouble u2);
void(APIENTRY *qglMapGrid1f)(GLint un, GLfloat u1, GLfloat u2);
void(APIENTRY *qglMapGrid2d)(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
void(APIENTRY *qglMapGrid2f)(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
void(APIENTRY *qglMaterialf)(GLenum face, GLenum pname, GLfloat param);
void(APIENTRY *qglMaterialfv)(GLenum face, GLenum pname, const GLfloat *params);
void(APIENTRY *qglMateriali)(GLenum face, GLenum pname, GLint param);
void(APIENTRY *qglMaterialiv)(GLenum face, GLenum pname, const GLint *params);
void(APIENTRY *qglMatrixMode)(GLenum mode);
void(APIENTRY *qglMultMatrixd)(const GLdouble *m);
void(APIENTRY *qglMultMatrixf)(const GLfloat *m);
void(APIENTRY *qglNewList)(GLuint list, GLenum mode);
void(APIENTRY *qglNormal3b)(GLbyte nx, GLbyte ny, GLbyte nz);
void(APIENTRY *qglNormal3bv)(const GLbyte *v);
void(APIENTRY *qglNormal3d)(GLdouble nx, GLdouble ny, GLdouble nz);
void(APIENTRY *qglNormal3dv)(const GLdouble *v);
void(APIENTRY *qglNormal3f)(GLfloat nx, GLfloat ny, GLfloat nz);
void(APIENTRY *qglNormal3fv)(const GLfloat *v);
void(APIENTRY *qglNormal3i)(GLint nx, GLint ny, GLint nz);
void(APIENTRY *qglNormal3iv)(const GLint *v);
void(APIENTRY *qglNormal3s)(GLshort nx, GLshort ny, GLshort nz);
void(APIENTRY *qglNormal3sv)(const GLshort *v);
void(APIENTRY *qglNormalPointer)(GLenum type, GLsizei stride, const GLvoid *pointer);
void(APIENTRY *qglOrtho)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
void(APIENTRY *qglPassThrough)(GLfloat token);
void(APIENTRY *qglPixelMapfv)(GLenum map, GLsizei mapsize, const GLfloat *values);
void(APIENTRY *qglPixelMapuiv)(GLenum map, GLsizei mapsize, const GLuint *values);
void(APIENTRY *qglPixelMapusv)(GLenum map, GLsizei mapsize, const GLushort *values);
void(APIENTRY *qglPixelStoref)(GLenum pname, GLfloat param);
void(APIENTRY *qglPixelStorei)(GLenum pname, GLint param);
void(APIENTRY *qglPixelTransferf)(GLenum pname, GLfloat param);
void(APIENTRY *qglPixelTransferi)(GLenum pname, GLint param);
void(APIENTRY *qglPixelZoom)(GLfloat xfactor, GLfloat yfactor);
void(APIENTRY *qglPointSize)(GLfloat size);
void(APIENTRY *qglPolygonMode)(GLenum face, GLenum mode);
void(APIENTRY *qglPolygonOffset)(GLfloat factor, GLfloat units);
void(APIENTRY *qglPolygonStipple)(const GLubyte *mask);
void(APIENTRY *qglPopAttrib)(void);
void(APIENTRY *qglPopClientAttrib)(void);
void(APIENTRY *qglPopMatrix)(void);
void(APIENTRY *qglPopName)(void);
void(APIENTRY *qglPrioritizeTextures)(GLsizei n, const GLuint *textures, const GLclampf *priorities);
void(APIENTRY *qglPushAttrib)(GLbitfield mask);
void(APIENTRY *qglPushClientAttrib)(GLbitfield mask);
void(APIENTRY *qglPushMatrix)(void);
void(APIENTRY *qglPushName)(GLuint name);
void(APIENTRY *qglRasterPos2d)(GLdouble x, GLdouble y);
void(APIENTRY *qglRasterPos2dv)(const GLdouble *v);
void(APIENTRY *qglRasterPos2f)(GLfloat x, GLfloat y);
void(APIENTRY *qglRasterPos2fv)(const GLfloat *v);
void(APIENTRY *qglRasterPos2i)(GLint x, GLint y);
void(APIENTRY *qglRasterPos2iv)(const GLint *v);
void(APIENTRY *qglRasterPos2s)(GLshort x, GLshort y);
void(APIENTRY *qglRasterPos2sv)(const GLshort *v);
void(APIENTRY *qglRasterPos3d)(GLdouble x, GLdouble y, GLdouble z);
void(APIENTRY *qglRasterPos3dv)(const GLdouble *v);
void(APIENTRY *qglRasterPos3f)(GLfloat x, GLfloat y, GLfloat z);
void(APIENTRY *qglRasterPos3fv)(const GLfloat *v);
void(APIENTRY *qglRasterPos3i)(GLint x, GLint y, GLint z);
void(APIENTRY *qglRasterPos3iv)(const GLint *v);
void(APIENTRY *qglRasterPos3s)(GLshort x, GLshort y, GLshort z);
void(APIENTRY *qglRasterPos3sv)(const GLshort *v);
void(APIENTRY *qglRasterPos4d)(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void(APIENTRY *qglRasterPos4dv)(const GLdouble *v);
void(APIENTRY *qglRasterPos4f)(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void(APIENTRY *qglRasterPos4fv)(const GLfloat *v);
void(APIENTRY *qglRasterPos4i)(GLint x, GLint y, GLint z, GLint w);
void(APIENTRY *qglRasterPos4iv)(const GLint *v);
void(APIENTRY *qglRasterPos4s)(GLshort x, GLshort y, GLshort z, GLshort w);
void(APIENTRY *qglRasterPos4sv)(const GLshort *v);
void(APIENTRY *qglReadBuffer)(GLenum mode);
void(APIENTRY *qglReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type,
                              GLvoid *pixels);
void(APIENTRY *qglRectd)(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
void(APIENTRY *qglRectdv)(const GLdouble *v1, const GLdouble *v2);
void(APIENTRY *qglRectf)(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
void(APIENTRY *qglRectfv)(const GLfloat *v1, const GLfloat *v2);
void(APIENTRY *qglRecti)(GLint x1, GLint y1, GLint x2, GLint y2);
void(APIENTRY *qglRectiv)(const GLint *v1, const GLint *v2);
void(APIENTRY *qglRects)(GLshort x1, GLshort y1, GLshort x2, GLshort y2);
void(APIENTRY *qglRectsv)(const GLshort *v1, const GLshort *v2);
GLint(APIENTRY *qglRenderMode)(GLenum mode);
void(APIENTRY *qglRotated)(GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
void(APIENTRY *qglRotatef)(GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
void(APIENTRY *qglScaled)(GLdouble x, GLdouble y, GLdouble z);
void(APIENTRY *qglScalef)(GLfloat x, GLfloat y, GLfloat z);
void(APIENTRY *qglScissor)(GLint x, GLint y, GLsizei width, GLsizei height);
void(APIENTRY *qglSelectBuffer)(GLsizei size, GLuint *buffer);
void(APIENTRY *qglShadeModel)(GLenum mode);
void(APIENTRY *qglStencilFunc)(GLenum func, GLint ref, GLuint mask);
void(APIENTRY *qglStencilMask)(GLuint mask);
void(APIENTRY *qglStencilOp)(GLenum fail, GLenum zfail, GLenum zpass);
void(APIENTRY *qglTexCoord1d)(GLdouble s);
void(APIENTRY *qglTexCoord1dv)(const GLdouble *v);
void(APIENTRY *qglTexCoord1f)(GLfloat s);
void(APIENTRY *qglTexCoord1fv)(const GLfloat *v);
void(APIENTRY *qglTexCoord1i)(GLint s);
void(APIENTRY *qglTexCoord1iv)(const GLint *v);
void(APIENTRY *qglTexCoord1s)(GLshort s);
void(APIENTRY *qglTexCoord1sv)(const GLshort *v);
void(APIENTRY *qglTexCoord2d)(GLdouble s, GLdouble t);
void(APIENTRY *qglTexCoord2dv)(const GLdouble *v);
void(APIENTRY *qglTexCoord2f)(GLfloat s, GLfloat t);
void(APIENTRY *qglTexCoord2fv)(const GLfloat *v);
void(APIENTRY *qglTexCoord2i)(GLint s, GLint t);
void(APIENTRY *qglTexCoord2iv)(const GLint *v);
void(APIENTRY *qglTexCoord2s)(GLshort s, GLshort t);
void(APIENTRY *qglTexCoord2sv)(const GLshort *v);
void(APIENTRY *qglTexCoord3d)(GLdouble s, GLdouble t, GLdouble r);
void(APIENTRY *qglTexCoord3dv)(const GLdouble *v);
void(APIENTRY *qglTexCoord3f)(GLfloat s, GLfloat t, GLfloat r);
void(APIENTRY *qglTexCoord3fv)(const GLfloat *v);
void(APIENTRY *qglTexCoord3i)(GLint s, GLint t, GLint r);
void(APIENTRY *qglTexCoord3iv)(const GLint *v);
void(APIENTRY *qglTexCoord3s)(GLshort s, GLshort t, GLshort r);
void(APIENTRY *qglTexCoord3sv)(const GLshort *v);
void(APIENTRY *qglTexCoord4d)(GLdouble s, GLdouble t, GLdouble r, GLdouble q);
void(APIENTRY *qglTexCoord4dv)(const GLdouble *v);
void(APIENTRY *qglTexCoord4f)(GLfloat s, GLfloat t, GLfloat r, GLfloat q);
void(APIENTRY *qglTexCoord4fv)(const GLfloat *v);
void(APIENTRY *qglTexCoord4i)(GLint s, GLint t, GLint r, GLint q);
void(APIENTRY *qglTexCoord4iv)(const GLint *v);
void(APIENTRY *qglTexCoord4s)(GLshort s, GLshort t, GLshort r, GLshort q);
void(APIENTRY *qglTexCoord4sv)(const GLshort *v);
void(APIENTRY *qglTexCoordPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void(APIENTRY *qglTexEnvf)(GLenum target, GLenum pname, GLfloat param);
void(APIENTRY *qglTexEnvfv)(GLenum target, GLenum pname, const GLfloat *params);
void(APIENTRY *qglTexEnvi)(GLenum target, GLenum pname, GLint param);
void(APIENTRY *qglTexEnviv)(GLenum target, GLenum pname, const GLint *params);
void(APIENTRY *qglTexGend)(GLenum coord, GLenum pname, GLdouble param);
void(APIENTRY *qglTexGendv)(GLenum coord, GLenum pname, const GLdouble *params);
void(APIENTRY *qglTexGenf)(GLenum coord, GLenum pname, GLfloat param);
void(APIENTRY *qglTexGenfv)(GLenum coord, GLenum pname, const GLfloat *params);
void(APIENTRY *qglTexGeni)(GLenum coord, GLenum pname, GLint param);
void(APIENTRY *qglTexGeniv)(GLenum coord, GLenum pname, const GLint *params);
void(APIENTRY *qglTexImage1D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border,
                              GLenum format, GLenum type, const GLvoid *pixels);
void(APIENTRY *qglTexImage2D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height,
                              GLint border, GLenum format, GLenum type, const GLvoid *pixels);
void(APIENTRY *qglTexParameterf)(GLenum target, GLenum pname, GLfloat param);
void(APIENTRY *qglTexParameterfv)(GLenum target, GLenum pname, const GLfloat *params);
void(APIENTRY *qglTexParameteri)(GLenum target, GLenum pname, GLint param);
void(APIENTRY *qglTexParameteriv)(GLenum target, GLenum pname, const GLint *params);
void(APIENTRY *qglTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type,
                                 const GLvoid *pixels);
void(APIENTRY *qglTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width,
                                 GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
void(APIENTRY *qglTranslated)(GLdouble x, GLdouble y, GLdouble z);
void(APIENTRY *qglTranslatef)(GLfloat x, GLfloat y, GLfloat z);
void(APIENTRY *qglVertex2d)(GLdouble x, GLdouble y);
void(APIENTRY *qglVertex2dv)(const GLdouble *v);
void(APIENTRY *qglVertex2f)(GLfloat x, GLfloat y);
void(APIENTRY *qglVertex2fv)(const GLfloat *v);
void(APIENTRY *qglVertex2i)(GLint x, GLint y);
void(APIENTRY *qglVertex2iv)(const GLint *v);
void(APIENTRY *qglVertex2s)(GLshort x, GLshort y);
void(APIENTRY *qglVertex2sv)(const GLshort *v);
void(APIENTRY *qglVertex3d)(GLdouble x, GLdouble y, GLdouble z);
void(APIENTRY *qglVertex3dv)(const GLdouble *v);
void(APIENTRY *qglVertex3f)(GLfloat x, GLfloat y, GLfloat z);
void(APIENTRY *qglVertex3fv)(const GLfloat *v);
void(APIENTRY *qglVertex3i)(GLint x, GLint y, GLint z);
void(APIENTRY *qglVertex3iv)(const GLint *v);
void(APIENTRY *qglVertex3s)(GLshort x, GLshort y, GLshort z);
void(APIENTRY *qglVertex3sv)(const GLshort *v);
void(APIENTRY *qglVertex4d)(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void(APIENTRY *qglVertex4dv)(const GLdouble *v);
void(APIENTRY *qglVertex4f)(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void(APIENTRY *qglVertex4fv)(const GLfloat *v);
void(APIENTRY *qglVertex4i)(GLint x, GLint y, GLint z, GLint w);
void(APIENTRY *qglVertex4iv)(const GLint *v);
void(APIENTRY *qglVertex4s)(GLshort x, GLshort y, GLshort z, GLshort w);
void(APIENTRY *qglVertex4sv)(const GLshort *v);
void(APIENTRY *qglVertexPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void(APIENTRY *qglViewport)(GLint x, GLint y, GLsizei width, GLsizei height);

void(APIENTRY *qglLockArraysEXT)(int, int);
void(APIENTRY *qglUnlockArraysEXT)(void);

BOOL(WINAPI *qwglSwapIntervalEXT)(int interval);
BOOL(WINAPI *qwglGetDeviceGammaRampEXT)(unsigned char *, unsigned char *, unsigned char *);
BOOL(WINAPI *qwglSetDeviceGammaRampEXT)(const unsigned char *, const unsigned char *, const unsigned char *);
void(APIENTRY *qglPointParameterfEXT)(GLenum param, GLfloat value);
void(APIENTRY *qglPointParameterfvEXT)(GLenum param, const GLfloat *value);
void(APIENTRY *qglColorTableEXT)(int, int, int, int, int, const void *);
void(APIENTRY *qglSelectTextureSGIS)(GLenum);
void(APIENTRY *qglMTexCoord2fSGIS)(GLenum, GLfloat, GLfloat);

/*
** QGL_Shutdown
**
** Unloads the specified DLL then nulls out all the proc pointers.
*/
void QGL_Shutdown(void) {
  qglAccum = NULL;
  qglAlphaFunc = NULL;
  qglAreTexturesResident = NULL;
  qglArrayElement = NULL;
  qglBegin = NULL;
  qglBindTexture = NULL;
  qglBitmap = NULL;
  qglBlendFunc = NULL;
  qglCallList = NULL;
  qglCallLists = NULL;
  qglClear = NULL;
  qglClearAccum = NULL;
  qglClearColor = NULL;
  qglClearDepth = NULL;
  qglClearIndex = NULL;
  qglClearStencil = NULL;
  qglClipPlane = NULL;
  qglColor3b = NULL;
  qglColor3bv = NULL;
  qglColor3d = NULL;
  qglColor3dv = NULL;
  qglColor3f = NULL;
  qglColor3fv = NULL;
  qglColor3i = NULL;
  qglColor3iv = NULL;
  qglColor3s = NULL;
  qglColor3sv = NULL;
  qglColor3ub = NULL;
  qglColor3ubv = NULL;
  qglColor3ui = NULL;
  qglColor3uiv = NULL;
  qglColor3us = NULL;
  qglColor3usv = NULL;
  qglColor4b = NULL;
  qglColor4bv = NULL;
  qglColor4d = NULL;
  qglColor4dv = NULL;
  qglColor4f = NULL;
  qglColor4fv = NULL;
  qglColor4i = NULL;
  qglColor4iv = NULL;
  qglColor4s = NULL;
  qglColor4sv = NULL;
  qglColor4ub = NULL;
  qglColor4ubv = NULL;
  qglColor4ui = NULL;
  qglColor4uiv = NULL;
  qglColor4us = NULL;
  qglColor4usv = NULL;
  qglColorMask = NULL;
  qglColorMaterial = NULL;
  qglColorPointer = NULL;
  qglCopyPixels = NULL;
  qglCopyTexImage1D = NULL;
  qglCopyTexImage2D = NULL;
  qglCopyTexSubImage1D = NULL;
  qglCopyTexSubImage2D = NULL;
  qglCullFace = NULL;
  qglDeleteLists = NULL;
  qglDeleteTextures = NULL;
  qglDepthFunc = NULL;
  qglDepthMask = NULL;
  qglDepthRange = NULL;
  qglDisable = NULL;
  qglDisableClientState = NULL;
  qglDrawArrays = NULL;
  qglDrawBuffer = NULL;
  qglDrawElements = NULL;
  qglDrawPixels = NULL;
  qglEdgeFlag = NULL;
  qglEdgeFlagPointer = NULL;
  qglEdgeFlagv = NULL;
  qglEnable = NULL;
  qglEnableClientState = NULL;
  qglEnd = NULL;
  qglEndList = NULL;
  qglEvalCoord1d = NULL;
  qglEvalCoord1dv = NULL;
  qglEvalCoord1f = NULL;
  qglEvalCoord1fv = NULL;
  qglEvalCoord2d = NULL;
  qglEvalCoord2dv = NULL;
  qglEvalCoord2f = NULL;
  qglEvalCoord2fv = NULL;
  qglEvalMesh1 = NULL;
  qglEvalMesh2 = NULL;
  qglEvalPoint1 = NULL;
  qglEvalPoint2 = NULL;
  qglFeedbackBuffer = NULL;
  qglFinish = NULL;
  qglFlush = NULL;
  qglFogf = NULL;
  qglFogfv = NULL;
  qglFogi = NULL;
  qglFogiv = NULL;
  qglFrontFace = NULL;
  qglFrustum = NULL;
  qglGenLists = NULL;
  qglGenTextures = NULL;
  qglGetBooleanv = NULL;
  qglGetClipPlane = NULL;
  qglGetDoublev = NULL;
  qglGetError = NULL;
  qglGetFloatv = NULL;
  qglGetIntegerv = NULL;
  qglGetLightfv = NULL;
  qglGetLightiv = NULL;
  qglGetMapdv = NULL;
  qglGetMapfv = NULL;
  qglGetMapiv = NULL;
  qglGetMaterialfv = NULL;
  qglGetMaterialiv = NULL;
  qglGetPixelMapfv = NULL;
  qglGetPixelMapuiv = NULL;
  qglGetPixelMapusv = NULL;
  qglGetPointerv = NULL;
  qglGetPolygonStipple = NULL;
  qglGetString = NULL;
  qglGetTexEnvfv = NULL;
  qglGetTexEnviv = NULL;
  qglGetTexGendv = NULL;
  qglGetTexGenfv = NULL;
  qglGetTexGeniv = NULL;
  qglGetTexImage = NULL;
  qglGetTexLevelParameterfv = NULL;
  qglGetTexLevelParameteriv = NULL;
  qglGetTexParameterfv = NULL;
  qglGetTexParameteriv = NULL;
  qglHint = NULL;
  qglIndexMask = NULL;
  qglIndexPointer = NULL;
  qglIndexd = NULL;
  qglIndexdv = NULL;
  qglIndexf = NULL;
  qglIndexfv = NULL;
  qglIndexi = NULL;
  qglIndexiv = NULL;
  qglIndexs = NULL;
  qglIndexsv = NULL;
  qglIndexub = NULL;
  qglIndexubv = NULL;
  qglInitNames = NULL;
  qglInterleavedArrays = NULL;
  qglIsEnabled = NULL;
  qglIsList = NULL;
  qglIsTexture = NULL;
  qglLightModelf = NULL;
  qglLightModelfv = NULL;
  qglLightModeli = NULL;
  qglLightModeliv = NULL;
  qglLightf = NULL;
  qglLightfv = NULL;
  qglLighti = NULL;
  qglLightiv = NULL;
  qglLineStipple = NULL;
  qglLineWidth = NULL;
  qglListBase = NULL;
  qglLoadIdentity = NULL;
  qglLoadMatrixd = NULL;
  qglLoadMatrixf = NULL;
  qglLoadName = NULL;
  qglLogicOp = NULL;
  qglMap1d = NULL;
  qglMap1f = NULL;
  qglMap2d = NULL;
  qglMap2f = NULL;
  qglMapGrid1d = NULL;
  qglMapGrid1f = NULL;
  qglMapGrid2d = NULL;
  qglMapGrid2f = NULL;
  qglMaterialf = NULL;
  qglMaterialfv = NULL;
  qglMateriali = NULL;
  qglMaterialiv = NULL;
  qglMatrixMode = NULL;
  qglMultMatrixd = NULL;
  qglMultMatrixf = NULL;
  qglNewList = NULL;
  qglNormal3b = NULL;
  qglNormal3bv = NULL;
  qglNormal3d = NULL;
  qglNormal3dv = NULL;
  qglNormal3f = NULL;
  qglNormal3fv = NULL;
  qglNormal3i = NULL;
  qglNormal3iv = NULL;
  qglNormal3s = NULL;
  qglNormal3sv = NULL;
  qglNormalPointer = NULL;
  qglOrtho = NULL;
  qglPassThrough = NULL;
  qglPixelMapfv = NULL;
  qglPixelMapuiv = NULL;
  qglPixelMapusv = NULL;
  qglPixelStoref = NULL;
  qglPixelStorei = NULL;
  qglPixelTransferf = NULL;
  qglPixelTransferi = NULL;
  qglPixelZoom = NULL;
  qglPointSize = NULL;
  qglPolygonMode = NULL;
  qglPolygonOffset = NULL;
  qglPolygonStipple = NULL;
  qglPopAttrib = NULL;
  qglPopClientAttrib = NULL;
  qglPopMatrix = NULL;
  qglPopName = NULL;
  qglPrioritizeTextures = NULL;
  qglPushAttrib = NULL;
  qglPushClientAttrib = NULL;
  qglPushMatrix = NULL;
  qglPushName = NULL;
  qglRasterPos2d = NULL;
  qglRasterPos2dv = NULL;
  qglRasterPos2f = NULL;
  qglRasterPos2fv = NULL;
  qglRasterPos2i = NULL;
  qglRasterPos2iv = NULL;
  qglRasterPos2s = NULL;
  qglRasterPos2sv = NULL;
  qglRasterPos3d = NULL;
  qglRasterPos3dv = NULL;
  qglRasterPos3f = NULL;
  qglRasterPos3fv = NULL;
  qglRasterPos3i = NULL;
  qglRasterPos3iv = NULL;
  qglRasterPos3s = NULL;
  qglRasterPos3sv = NULL;
  qglRasterPos4d = NULL;
  qglRasterPos4dv = NULL;
  qglRasterPos4f = NULL;
  qglRasterPos4fv = NULL;
  qglRasterPos4i = NULL;
  qglRasterPos4iv = NULL;
  qglRasterPos4s = NULL;
  qglRasterPos4sv = NULL;
  qglReadBuffer = NULL;
  qglReadPixels = NULL;
  qglRectd = NULL;
  qglRectdv = NULL;
  qglRectf = NULL;
  qglRectfv = NULL;
  qglRecti = NULL;
  qglRectiv = NULL;
  qglRects = NULL;
  qglRectsv = NULL;
  qglRenderMode = NULL;
  qglRotated = NULL;
  qglRotatef = NULL;
  qglScaled = NULL;
  qglScalef = NULL;
  qglScissor = NULL;
  qglSelectBuffer = NULL;
  qglShadeModel = NULL;
  qglStencilFunc = NULL;
  qglStencilMask = NULL;
  qglStencilOp = NULL;
  qglTexCoord1d = NULL;
  qglTexCoord1dv = NULL;
  qglTexCoord1f = NULL;
  qglTexCoord1fv = NULL;
  qglTexCoord1i = NULL;
  qglTexCoord1iv = NULL;
  qglTexCoord1s = NULL;
  qglTexCoord1sv = NULL;
  qglTexCoord2d = NULL;
  qglTexCoord2dv = NULL;
  qglTexCoord2f = NULL;
  qglTexCoord2fv = NULL;
  qglTexCoord2i = NULL;
  qglTexCoord2iv = NULL;
  qglTexCoord2s = NULL;
  qglTexCoord2sv = NULL;
  qglTexCoord3d = NULL;
  qglTexCoord3dv = NULL;
  qglTexCoord3f = NULL;
  qglTexCoord3fv = NULL;
  qglTexCoord3i = NULL;
  qglTexCoord3iv = NULL;
  qglTexCoord3s = NULL;
  qglTexCoord3sv = NULL;
  qglTexCoord4d = NULL;
  qglTexCoord4dv = NULL;
  qglTexCoord4f = NULL;
  qglTexCoord4fv = NULL;
  qglTexCoord4i = NULL;
  qglTexCoord4iv = NULL;
  qglTexCoord4s = NULL;
  qglTexCoord4sv = NULL;
  qglTexCoordPointer = NULL;
  qglTexEnvf = NULL;
  qglTexEnvfv = NULL;
  qglTexEnvi = NULL;
  qglTexEnviv = NULL;
  qglTexGend = NULL;
  qglTexGendv = NULL;
  qglTexGenf = NULL;
  qglTexGenfv = NULL;
  qglTexGeni = NULL;
  qglTexGeniv = NULL;
  qglTexImage1D = NULL;
  qglTexImage2D = NULL;
  qglTexParameterf = NULL;
  qglTexParameterfv = NULL;
  qglTexParameteri = NULL;
  qglTexParameteriv = NULL;
  qglTexSubImage1D = NULL;
  qglTexSubImage2D = NULL;
  qglTranslated = NULL;
  qglTranslatef = NULL;
  qglVertex2d = NULL;
  qglVertex2dv = NULL;
  qglVertex2f = NULL;
  qglVertex2fv = NULL;
  qglVertex2i = NULL;
  qglVertex2iv = NULL;
  qglVertex2s = NULL;
  qglVertex2sv = NULL;
  qglVertex3d = NULL;
  qglVertex3dv = NULL;
  qglVertex3f = NULL;
  qglVertex3fv = NULL;
  qglVertex3i = NULL;
  qglVertex3iv = NULL;
  qglVertex3s = NULL;
  qglVertex3sv = NULL;
  qglVertex4d = NULL;
  qglVertex4dv = NULL;
  qglVertex4f = NULL;
  qglVertex4fv = NULL;
  qglVertex4i = NULL;
  qglVertex4iv = NULL;
  qglVertex4s = NULL;
  qglVertex4sv = NULL;
  qglVertexPointer = NULL;
  qglViewport = NULL;
}

#define GPA(a) glfwGetProcAddress(a)

/*
** QGL_Init
**
** This is responsible for binding our qgl function pointers to
** the appropriate GL stuff.  In Windows this means doing a
** LoadLibrary and a bunch of calls to GetProcAddress.  On other
** operating systems we need to do the right thing, whatever that
** might be.
**
*/
bool QGL_Init(const char *dllname) {
#define INIT_DLL_TO_QGL(a)                                                                                             \
  do {                                                                                                                 \
    *(void **)&qgl##a = GPA("gl" #a);                                                                                  \
  } while(false)

  INIT_DLL_TO_QGL(Accum);
  INIT_DLL_TO_QGL(AlphaFunc);
  INIT_DLL_TO_QGL(AreTexturesResident);
  INIT_DLL_TO_QGL(ArrayElement);
  INIT_DLL_TO_QGL(Begin);
  INIT_DLL_TO_QGL(BindTexture);
  INIT_DLL_TO_QGL(Bitmap);
  INIT_DLL_TO_QGL(BlendFunc);
  INIT_DLL_TO_QGL(CallList);
  INIT_DLL_TO_QGL(CallLists);
  INIT_DLL_TO_QGL(Clear);
  INIT_DLL_TO_QGL(ClearAccum);
  INIT_DLL_TO_QGL(ClearColor);
  INIT_DLL_TO_QGL(ClearDepth);
  INIT_DLL_TO_QGL(ClearIndex);
  INIT_DLL_TO_QGL(ClearStencil);
  INIT_DLL_TO_QGL(ClipPlane);
  INIT_DLL_TO_QGL(Color3b);
  INIT_DLL_TO_QGL(Color3bv);
  INIT_DLL_TO_QGL(Color3d);
  INIT_DLL_TO_QGL(Color3dv);
  INIT_DLL_TO_QGL(Color3f);
  INIT_DLL_TO_QGL(Color3fv);
  INIT_DLL_TO_QGL(Color3i);
  INIT_DLL_TO_QGL(Color3iv);
  INIT_DLL_TO_QGL(Color3s);
  INIT_DLL_TO_QGL(Color3sv);
  INIT_DLL_TO_QGL(Color3ub);
  INIT_DLL_TO_QGL(Color3ubv);
  INIT_DLL_TO_QGL(Color3ui);
  INIT_DLL_TO_QGL(Color3uiv);
  INIT_DLL_TO_QGL(Color3us);
  INIT_DLL_TO_QGL(Color3usv);
  INIT_DLL_TO_QGL(Color4b);
  INIT_DLL_TO_QGL(Color4bv);
  INIT_DLL_TO_QGL(Color4d);
  INIT_DLL_TO_QGL(Color4dv);
  INIT_DLL_TO_QGL(Color4f);
  INIT_DLL_TO_QGL(Color4fv);
  INIT_DLL_TO_QGL(Color4i);
  INIT_DLL_TO_QGL(Color4iv);
  INIT_DLL_TO_QGL(Color4s);
  INIT_DLL_TO_QGL(Color4sv);
  INIT_DLL_TO_QGL(Color4ub);
  INIT_DLL_TO_QGL(Color4ubv);
  INIT_DLL_TO_QGL(Color4ui);
  INIT_DLL_TO_QGL(Color4uiv);
  INIT_DLL_TO_QGL(Color4us);
  INIT_DLL_TO_QGL(Color4usv);
  INIT_DLL_TO_QGL(ColorMask);
  INIT_DLL_TO_QGL(ColorMaterial);
  INIT_DLL_TO_QGL(ColorPointer);
  INIT_DLL_TO_QGL(CopyPixels);
  INIT_DLL_TO_QGL(CopyTexImage1D);
  INIT_DLL_TO_QGL(CopyTexImage2D);
  INIT_DLL_TO_QGL(CopyTexSubImage1D);
  INIT_DLL_TO_QGL(CopyTexSubImage2D);
  INIT_DLL_TO_QGL(CullFace);
  INIT_DLL_TO_QGL(DeleteLists);
  INIT_DLL_TO_QGL(DeleteTextures);
  INIT_DLL_TO_QGL(DepthFunc);
  INIT_DLL_TO_QGL(DepthMask);
  INIT_DLL_TO_QGL(DepthRange);
  INIT_DLL_TO_QGL(Disable);
  INIT_DLL_TO_QGL(DisableClientState);
  INIT_DLL_TO_QGL(DrawArrays);
  INIT_DLL_TO_QGL(DrawBuffer);
  INIT_DLL_TO_QGL(DrawElements);
  INIT_DLL_TO_QGL(DrawPixels);
  INIT_DLL_TO_QGL(EdgeFlag);
  INIT_DLL_TO_QGL(EdgeFlagPointer);
  INIT_DLL_TO_QGL(EdgeFlagv);
  INIT_DLL_TO_QGL(Enable);
  INIT_DLL_TO_QGL(EnableClientState);
  INIT_DLL_TO_QGL(End);
  INIT_DLL_TO_QGL(EndList);
  INIT_DLL_TO_QGL(EvalCoord1d);
  INIT_DLL_TO_QGL(EvalCoord1dv);
  INIT_DLL_TO_QGL(EvalCoord1f);
  INIT_DLL_TO_QGL(EvalCoord1fv);
  INIT_DLL_TO_QGL(EvalCoord2d);
  INIT_DLL_TO_QGL(EvalCoord2dv);
  INIT_DLL_TO_QGL(EvalCoord2f);
  INIT_DLL_TO_QGL(EvalCoord2fv);
  INIT_DLL_TO_QGL(EvalMesh1);
  INIT_DLL_TO_QGL(EvalMesh2);
  INIT_DLL_TO_QGL(EvalPoint1);
  INIT_DLL_TO_QGL(EvalPoint2);
  INIT_DLL_TO_QGL(FeedbackBuffer);
  INIT_DLL_TO_QGL(Finish);
  INIT_DLL_TO_QGL(Flush);
  INIT_DLL_TO_QGL(Fogf);
  INIT_DLL_TO_QGL(Fogfv);
  INIT_DLL_TO_QGL(Fogi);
  INIT_DLL_TO_QGL(Fogiv);
  INIT_DLL_TO_QGL(FrontFace);
  INIT_DLL_TO_QGL(Frustum);
  INIT_DLL_TO_QGL(GenLists);
  INIT_DLL_TO_QGL(GenTextures);
  INIT_DLL_TO_QGL(GetBooleanv);
  INIT_DLL_TO_QGL(GetClipPlane);
  INIT_DLL_TO_QGL(GetDoublev);
  INIT_DLL_TO_QGL(GetError);
  INIT_DLL_TO_QGL(GetFloatv);
  INIT_DLL_TO_QGL(GetIntegerv);
  INIT_DLL_TO_QGL(GetLightfv);
  INIT_DLL_TO_QGL(GetLightiv);
  INIT_DLL_TO_QGL(GetMapdv);
  INIT_DLL_TO_QGL(GetMapfv);
  INIT_DLL_TO_QGL(GetMapiv);
  INIT_DLL_TO_QGL(GetMaterialfv);
  INIT_DLL_TO_QGL(GetMaterialiv);
  INIT_DLL_TO_QGL(GetPixelMapfv);
  INIT_DLL_TO_QGL(GetPixelMapuiv);
  INIT_DLL_TO_QGL(GetPixelMapusv);
  INIT_DLL_TO_QGL(GetPointerv);
  INIT_DLL_TO_QGL(GetPolygonStipple);
  INIT_DLL_TO_QGL(GetString);
  INIT_DLL_TO_QGL(GetTexEnvfv);
  INIT_DLL_TO_QGL(GetTexEnviv);
  INIT_DLL_TO_QGL(GetTexGendv);
  INIT_DLL_TO_QGL(GetTexGenfv);
  INIT_DLL_TO_QGL(GetTexGeniv);
  INIT_DLL_TO_QGL(GetTexImage);
  INIT_DLL_TO_QGL(GetTexLevelParameterfv);
  INIT_DLL_TO_QGL(GetTexLevelParameteriv);
  INIT_DLL_TO_QGL(GetTexParameterfv);
  INIT_DLL_TO_QGL(GetTexParameteriv);
  INIT_DLL_TO_QGL(Hint);
  INIT_DLL_TO_QGL(IndexMask);
  INIT_DLL_TO_QGL(IndexPointer);
  INIT_DLL_TO_QGL(Indexd);
  INIT_DLL_TO_QGL(Indexdv);
  INIT_DLL_TO_QGL(Indexf);
  INIT_DLL_TO_QGL(Indexfv);
  INIT_DLL_TO_QGL(Indexi);
  INIT_DLL_TO_QGL(Indexiv);
  INIT_DLL_TO_QGL(Indexs);
  INIT_DLL_TO_QGL(Indexsv);
  INIT_DLL_TO_QGL(Indexub);
  INIT_DLL_TO_QGL(Indexubv);
  INIT_DLL_TO_QGL(InitNames);
  INIT_DLL_TO_QGL(InterleavedArrays);
  INIT_DLL_TO_QGL(IsEnabled);
  INIT_DLL_TO_QGL(IsList);
  INIT_DLL_TO_QGL(IsTexture);
  INIT_DLL_TO_QGL(LightModelf);
  INIT_DLL_TO_QGL(LightModelfv);
  INIT_DLL_TO_QGL(LightModeli);
  INIT_DLL_TO_QGL(LightModeliv);
  INIT_DLL_TO_QGL(Lightf);
  INIT_DLL_TO_QGL(Lightfv);
  INIT_DLL_TO_QGL(Lighti);
  INIT_DLL_TO_QGL(Lightiv);
  INIT_DLL_TO_QGL(LineStipple);
  INIT_DLL_TO_QGL(LineWidth);
  INIT_DLL_TO_QGL(ListBase);
  INIT_DLL_TO_QGL(LoadIdentity);
  INIT_DLL_TO_QGL(LoadMatrixd);
  INIT_DLL_TO_QGL(LoadMatrixf);
  INIT_DLL_TO_QGL(LoadName);
  INIT_DLL_TO_QGL(LogicOp);
  INIT_DLL_TO_QGL(Map1d);
  INIT_DLL_TO_QGL(Map1f);
  INIT_DLL_TO_QGL(Map2d);
  INIT_DLL_TO_QGL(Map2f);
  INIT_DLL_TO_QGL(MapGrid1d);
  INIT_DLL_TO_QGL(MapGrid1f);
  INIT_DLL_TO_QGL(MapGrid2d);
  INIT_DLL_TO_QGL(MapGrid2f);
  INIT_DLL_TO_QGL(Materialf);
  INIT_DLL_TO_QGL(Materialfv);
  INIT_DLL_TO_QGL(Materiali);
  INIT_DLL_TO_QGL(Materialiv);
  INIT_DLL_TO_QGL(MatrixMode);
  INIT_DLL_TO_QGL(MultMatrixd);
  INIT_DLL_TO_QGL(MultMatrixf);
  INIT_DLL_TO_QGL(NewList);
  INIT_DLL_TO_QGL(Normal3b);
  INIT_DLL_TO_QGL(Normal3bv);
  INIT_DLL_TO_QGL(Normal3d);
  INIT_DLL_TO_QGL(Normal3dv);
  INIT_DLL_TO_QGL(Normal3f);
  INIT_DLL_TO_QGL(Normal3fv);
  INIT_DLL_TO_QGL(Normal3i);
  INIT_DLL_TO_QGL(Normal3iv);
  INIT_DLL_TO_QGL(Normal3s);
  INIT_DLL_TO_QGL(Normal3sv);
  INIT_DLL_TO_QGL(NormalPointer);
  INIT_DLL_TO_QGL(Ortho);
  INIT_DLL_TO_QGL(PassThrough);
  INIT_DLL_TO_QGL(PixelMapfv);
  INIT_DLL_TO_QGL(PixelMapuiv);
  INIT_DLL_TO_QGL(PixelMapusv);
  INIT_DLL_TO_QGL(PixelStoref);
  INIT_DLL_TO_QGL(PixelStorei);
  INIT_DLL_TO_QGL(PixelTransferf);
  INIT_DLL_TO_QGL(PixelTransferi);
  INIT_DLL_TO_QGL(PixelZoom);
  INIT_DLL_TO_QGL(PointSize);
  INIT_DLL_TO_QGL(PolygonMode);
  INIT_DLL_TO_QGL(PolygonOffset);
  INIT_DLL_TO_QGL(PolygonStipple);
  INIT_DLL_TO_QGL(PopAttrib);
  INIT_DLL_TO_QGL(PopClientAttrib);
  INIT_DLL_TO_QGL(PopMatrix);
  INIT_DLL_TO_QGL(PopName);
  INIT_DLL_TO_QGL(PrioritizeTextures);
  INIT_DLL_TO_QGL(PushAttrib);
  INIT_DLL_TO_QGL(PushClientAttrib);
  INIT_DLL_TO_QGL(PushMatrix);
  INIT_DLL_TO_QGL(PushName);
  INIT_DLL_TO_QGL(RasterPos2d);
  INIT_DLL_TO_QGL(RasterPos2dv);
  INIT_DLL_TO_QGL(RasterPos2f);
  INIT_DLL_TO_QGL(RasterPos2fv);
  INIT_DLL_TO_QGL(RasterPos2i);
  INIT_DLL_TO_QGL(RasterPos2iv);
  INIT_DLL_TO_QGL(RasterPos2s);
  INIT_DLL_TO_QGL(RasterPos2sv);
  INIT_DLL_TO_QGL(RasterPos3d);
  INIT_DLL_TO_QGL(RasterPos3dv);
  INIT_DLL_TO_QGL(RasterPos3f);
  INIT_DLL_TO_QGL(RasterPos3fv);
  INIT_DLL_TO_QGL(RasterPos3i);
  INIT_DLL_TO_QGL(RasterPos3iv);
  INIT_DLL_TO_QGL(RasterPos3s);
  INIT_DLL_TO_QGL(RasterPos3sv);
  INIT_DLL_TO_QGL(RasterPos4d);
  INIT_DLL_TO_QGL(RasterPos4dv);
  INIT_DLL_TO_QGL(RasterPos4f);
  INIT_DLL_TO_QGL(RasterPos4fv);
  INIT_DLL_TO_QGL(RasterPos4i);
  INIT_DLL_TO_QGL(RasterPos4iv);
  INIT_DLL_TO_QGL(RasterPos4s);
  INIT_DLL_TO_QGL(RasterPos4sv);
  INIT_DLL_TO_QGL(ReadBuffer);
  INIT_DLL_TO_QGL(ReadPixels);
  INIT_DLL_TO_QGL(Rectd);
  INIT_DLL_TO_QGL(Rectdv);
  INIT_DLL_TO_QGL(Rectf);
  INIT_DLL_TO_QGL(Rectfv);
  INIT_DLL_TO_QGL(Recti);
  INIT_DLL_TO_QGL(Rectiv);
  INIT_DLL_TO_QGL(Rects);
  INIT_DLL_TO_QGL(Rectsv);
  INIT_DLL_TO_QGL(RenderMode);
  INIT_DLL_TO_QGL(Rotated);
  INIT_DLL_TO_QGL(Rotatef);
  INIT_DLL_TO_QGL(Scaled);
  INIT_DLL_TO_QGL(Scalef);
  INIT_DLL_TO_QGL(Scissor);
  INIT_DLL_TO_QGL(SelectBuffer);
  INIT_DLL_TO_QGL(ShadeModel);
  INIT_DLL_TO_QGL(StencilFunc);
  INIT_DLL_TO_QGL(StencilMask);
  INIT_DLL_TO_QGL(StencilOp);
  INIT_DLL_TO_QGL(TexCoord1d);
  INIT_DLL_TO_QGL(TexCoord1dv);
  INIT_DLL_TO_QGL(TexCoord1f);
  INIT_DLL_TO_QGL(TexCoord1fv);
  INIT_DLL_TO_QGL(TexCoord1i);
  INIT_DLL_TO_QGL(TexCoord1iv);
  INIT_DLL_TO_QGL(TexCoord1s);
  INIT_DLL_TO_QGL(TexCoord1sv);
  INIT_DLL_TO_QGL(TexCoord2d);
  INIT_DLL_TO_QGL(TexCoord2dv);
  INIT_DLL_TO_QGL(TexCoord2f);
  INIT_DLL_TO_QGL(TexCoord2fv);
  INIT_DLL_TO_QGL(TexCoord2i);
  INIT_DLL_TO_QGL(TexCoord2iv);
  INIT_DLL_TO_QGL(TexCoord2s);
  INIT_DLL_TO_QGL(TexCoord2sv);
  INIT_DLL_TO_QGL(TexCoord3d);
  INIT_DLL_TO_QGL(TexCoord3dv);
  INIT_DLL_TO_QGL(TexCoord3f);
  INIT_DLL_TO_QGL(TexCoord3fv);
  INIT_DLL_TO_QGL(TexCoord3i);
  INIT_DLL_TO_QGL(TexCoord3iv);
  INIT_DLL_TO_QGL(TexCoord3s);
  INIT_DLL_TO_QGL(TexCoord3sv);
  INIT_DLL_TO_QGL(TexCoord4d);
  INIT_DLL_TO_QGL(TexCoord4dv);
  INIT_DLL_TO_QGL(TexCoord4f);
  INIT_DLL_TO_QGL(TexCoord4fv);
  INIT_DLL_TO_QGL(TexCoord4i);
  INIT_DLL_TO_QGL(TexCoord4iv);
  INIT_DLL_TO_QGL(TexCoord4s);
  INIT_DLL_TO_QGL(TexCoord4sv);
  INIT_DLL_TO_QGL(TexCoordPointer);
  INIT_DLL_TO_QGL(TexEnvf);
  INIT_DLL_TO_QGL(TexEnvfv);
  INIT_DLL_TO_QGL(TexEnvi);
  INIT_DLL_TO_QGL(TexEnviv);
  INIT_DLL_TO_QGL(TexGend);
  INIT_DLL_TO_QGL(TexGendv);
  INIT_DLL_TO_QGL(TexGenf);
  INIT_DLL_TO_QGL(TexGenfv);
  INIT_DLL_TO_QGL(TexGeni);
  INIT_DLL_TO_QGL(TexGeniv);
  INIT_DLL_TO_QGL(TexImage1D);
  INIT_DLL_TO_QGL(TexImage2D);
  INIT_DLL_TO_QGL(TexParameterf);
  INIT_DLL_TO_QGL(TexParameterfv);
  INIT_DLL_TO_QGL(TexParameteri);
  INIT_DLL_TO_QGL(TexParameteriv);
  INIT_DLL_TO_QGL(TexSubImage1D);
  INIT_DLL_TO_QGL(TexSubImage2D);
  INIT_DLL_TO_QGL(Translated);
  INIT_DLL_TO_QGL(Translatef);
  INIT_DLL_TO_QGL(Vertex2d);
  INIT_DLL_TO_QGL(Vertex2dv);
  INIT_DLL_TO_QGL(Vertex2f);
  INIT_DLL_TO_QGL(Vertex2fv);
  INIT_DLL_TO_QGL(Vertex2i);
  INIT_DLL_TO_QGL(Vertex2iv);
  INIT_DLL_TO_QGL(Vertex2s);
  INIT_DLL_TO_QGL(Vertex2sv);
  INIT_DLL_TO_QGL(Vertex3d);
  INIT_DLL_TO_QGL(Vertex3dv);
  INIT_DLL_TO_QGL(Vertex3f);
  INIT_DLL_TO_QGL(Vertex3fv);
  INIT_DLL_TO_QGL(Vertex3i);
  INIT_DLL_TO_QGL(Vertex3iv);
  INIT_DLL_TO_QGL(Vertex3s);
  INIT_DLL_TO_QGL(Vertex3sv);
  INIT_DLL_TO_QGL(Vertex4d);
  INIT_DLL_TO_QGL(Vertex4dv);
  INIT_DLL_TO_QGL(Vertex4f);
  INIT_DLL_TO_QGL(Vertex4fv);
  INIT_DLL_TO_QGL(Vertex4i);
  INIT_DLL_TO_QGL(Vertex4iv);
  INIT_DLL_TO_QGL(Vertex4s);
  INIT_DLL_TO_QGL(Vertex4sv);
  INIT_DLL_TO_QGL(VertexPointer);
  INIT_DLL_TO_QGL(Viewport);

#undef INIT_DLL_TO_QGL

  qwglSwapIntervalEXT = 0;
  qglPointParameterfEXT = 0;
  qglPointParameterfvEXT = 0;
  qglColorTableEXT = 0;
  qglSelectTextureSGIS = 0;
  qglMTexCoord2fSGIS = 0;

  return true;
}

void GLimp_EnableLogging(bool enable) {}

void GLimp_LogNewFrame(void) {}
